"""Add tle0 and audio/waterfall artifact columns

Revision ID: 95c693079f4d
Revises: 0001_initial
Create Date: 2026-06-23 17:55:56.825759

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "95c693079f4d"
down_revision: Union[str, Sequence[str], None] = "0001_initial"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "observations", sa.Column("audio_url", sa.String(length=256), nullable=True)
    )
    op.add_column(
        "observations", sa.Column("waterfall_url", sa.String(length=256), nullable=True)
    )
    op.add_column(
        "observations", sa.Column("tle_line0", sa.String(length=256), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("observations", "tle_line0")
    op.drop_column("observations", "waterfall_url")
    op.drop_column("observations", "audio_url")
    # ### end Alembic commands ###
