"""Drop audio blob columns

Revision ID: ac75b2b7d0a3
Revises: 95c693079f4d
Create Date: 2026-06-23 20:29:56.644184

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ac75b2b7d0a3"
down_revision: Union[str, Sequence[str], None] = "95c693079f4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("observations", "audio_data")
    op.drop_column("observations", "audio_content_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "observations",
        sa.Column(
            "audio_content_type",
            sa.VARCHAR(length=128),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "observations",
        sa.Column("audio_data", postgresql.BYTEA(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
